# Generated by Django 5.1.2 on 2024-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-created_at',), 'verbose_name': 'изображение товара', 'verbose_name_plural': 'изображения товаров'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=5, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='receive_type',
            field=models.CharField(choices=[('order', 'На заказ'), ('in_stock', 'В наличии'), ('pick_up', 'Самовывоз')], default='order', max_length=15, verbose_name='условия получения'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата добавления'),
        ),
    ]
